import {
  AlignmentConstraint,
  InstanceLayout,
  LayoutConstraint,
  LayoutNode,
  LeftConstraint,
  TopConstraint,
  isAlignmentConstraint,
  isLeftConstraint,
  isTopConstraint,
} from '../../layout/interfaces';

export interface BloomCanvas {
  width: number;
  height: number;
}

export interface BloomNode {
  id: string;
  label: string;
  type: string;
  width: number;
  height: number;
  color: string;
  icon?: string;
  showLabels: boolean;
  attributes: Record<string, string[]>;
  labels: Record<string, string[]>;
}

export interface BloomEdge {
  id: string;
  source: string;
  target: string;
  relation: string;
  label: string;
  color: string;
  weight?: number;
  style?: string;
  showLabel?: boolean;
}

export type BloomConstraint =
  | {
      kind: 'leftOf';
      left: string;
      right: string;
      minDistance: number;
      sourceType: string;
    }
  | {
      kind: 'above';
      top: string;
      bottom: string;
      minDistance: number;
      sourceType: string;
    }
  | {
      kind: 'align';
      axis: 'x' | 'y';
      node1: string;
      node2: string;
      sourceType: string;
    }
  | {
      kind: 'unsupported';
      sourceType: string;
      message: string;
    };

export interface BloomSpec {
  canvas: BloomCanvas;
  nodes: BloomNode[];
  edges: BloomEdge[];
  constraints: BloomConstraint[];
  disjunctiveConstraints: BloomConstraint[][][];
}

export interface PenroseBloomTranslation {
  /** Structured, JS-friendly Bloom-style spec. */
  spec: BloomSpec;
  /** Executable module-like source for consumers that want code output. */
  moduleSource: string;
}

/**
 * Emits a JS-oriented Bloom-style representation from an `InstanceLayout`.
 *
 * Unlike the WebCola translator (which produces runtime layout objects directly),
 * this translator serializes nodes/edges/constraints into a portable spec that can
 * be consumed by alternate JS rendering/optimization toolchains.
 */
export class PenroseBloomTranslator {
  translate(
    layout: InstanceLayout,
    width: number = 800,
    height: number = 600,
  ): PenroseBloomTranslation {
    const spec: BloomSpec = {
      canvas: { width, height },
      nodes: [...layout.nodes]
        .sort((a, b) => a.id.localeCompare(b.id))
        .map((node) => this.toNode(node)),
      edges: [...layout.edges]
        .sort((a, b) => a.id.localeCompare(b.id))
        .map((edge) => ({
          id: edge.id,
          source: edge.source.id,
          target: edge.target.id,
          relation: edge.relationName,
          label: edge.label,
          color: edge.color,
          weight: edge.weight,
          style: edge.style,
          showLabel: edge.showLabel,
        })),
      constraints: layout.constraints.map((constraint) => this.constraintToBloom(constraint)),
      disjunctiveConstraints: (layout.disjunctiveConstraints ?? []).map((disjunction) =>
        disjunction.alternatives.map((alternative) =>
          alternative.map((constraint) => this.constraintToBloom(constraint)),
        ),
      ),
    };

    const moduleSource = [
      '// Generated by PenroseBloomTranslator',
      'export const bloomSpec = ' + JSON.stringify(spec, null, 2) + ';',
      '',
      'export default bloomSpec;',
      '',
    ].join('\n');

    return { spec, moduleSource };
  }

  private toNode(node: LayoutNode): BloomNode {
    return {
      id: node.id,
      label: node.label,
      type: node.mostSpecificType,
      width: node.width,
      height: node.height,
      color: node.color,
      icon: node.icon,
      showLabels: node.showLabels,
      attributes: node.attributes ?? {},
      labels: node.labels ?? {},
    };
  }

  private constraintToBloom(constraint: LayoutConstraint): BloomConstraint {
    const sourceType = constraint.sourceConstraint.constructor?.name ?? 'UnknownConstraint';

    if (isLeftConstraint(constraint)) {
      return this.leftConstraint(constraint, sourceType);
    }

    if (isTopConstraint(constraint)) {
      return this.topConstraint(constraint, sourceType);
    }

    if (isAlignmentConstraint(constraint)) {
      return this.alignmentConstraint(constraint, sourceType);
    }

    return {
      kind: 'unsupported',
      sourceType,
      message: 'Constraint kind is not currently mapped by PenroseBloomTranslator.',
    };
  }

  private leftConstraint(constraint: LeftConstraint, sourceType: string): BloomConstraint {
    return {
      kind: 'leftOf',
      left: constraint.left.id,
      right: constraint.right.id,
      minDistance: constraint.minDistance,
      sourceType,
    };
  }

  private topConstraint(constraint: TopConstraint, sourceType: string): BloomConstraint {
    return {
      kind: 'above',
      top: constraint.top.id,
      bottom: constraint.bottom.id,
      minDistance: constraint.minDistance,
      sourceType,
    };
  }

  private alignmentConstraint(constraint: AlignmentConstraint, sourceType: string): BloomConstraint {
    return {
      kind: 'align',
      axis: constraint.axis,
      node1: constraint.node1.id,
      node2: constraint.node2.id,
      sourceType,
    };
  }
}
